/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as ConsultaRouteImport } from './routes/consulta'
import { Route as DicasRouteImport } from './routes/dicas'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as ModeracaoRouteImport } from './routes/moderacao'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as VeiculosRouteImport } from './routes/veiculos'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiVehiclesRouteImport } from './routes/api/vehicles'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiDocumentsIdRouteImport } from './routes/api/documents/$id'
import { Route as ApiDocumentsUploadRouteImport } from './routes/api/documents/upload'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultaRoute = ConsultaRouteImport.update({
  id: '/consulta',
  path: '/consulta',
  getParentRoute: () => rootRouteImport,
} as any)
const DicasRoute = DicasRouteImport.update({
  id: '/dicas',
  path: '/dicas',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const ModeracaoRoute = ModeracaoRouteImport.update({
  id: '/moderacao',
  path: '/moderacao',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const VeiculosRoute = VeiculosRouteImport.update({
  id: '/veiculos',
  path: '/veiculos',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVehiclesRoute = ApiVehiclesRouteImport.update({
  id: '/api/vehicles',
  path: '/api/vehicles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocumentsIdRoute = ApiDocumentsIdRouteImport.update({
  id: '/api/documents/$id',
  path: '/api/documents/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocumentsUploadRoute = ApiDocumentsUploadRouteImport.update({
  id: '/api/documents/upload',
  path: '/api/documents/upload',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/biblioteca': typeof BibliotecaRoute
  '/consulta': typeof ConsultaRoute
  '/dicas': typeof DicasRoute
  '/historico': typeof HistoricoRoute
  '/moderacao': typeof ModeracaoRoute
  '/perfil': typeof PerfilRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/veiculos': typeof VeiculosRoute
  '/videos': typeof VideosRoute
  '/api/health': typeof ApiHealthRoute
  '/api/vehicles': typeof ApiVehiclesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/documents/$id': typeof ApiDocumentsIdRoute
  '/api/documents/upload': typeof ApiDocumentsUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/biblioteca': typeof BibliotecaRoute
  '/consulta': typeof ConsultaRoute
  '/dicas': typeof DicasRoute
  '/historico': typeof HistoricoRoute
  '/moderacao': typeof ModeracaoRoute
  '/perfil': typeof PerfilRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/veiculos': typeof VeiculosRoute
  '/videos': typeof VideosRoute
  '/api/health': typeof ApiHealthRoute
  '/api/vehicles': typeof ApiVehiclesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/documents/$id': typeof ApiDocumentsIdRoute
  '/api/documents/upload': typeof ApiDocumentsUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/biblioteca': typeof BibliotecaRoute
  '/consulta': typeof ConsultaRoute
  '/dicas': typeof DicasRoute
  '/historico': typeof HistoricoRoute
  '/moderacao': typeof ModeracaoRoute
  '/perfil': typeof PerfilRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/veiculos': typeof VeiculosRoute
  '/videos': typeof VideosRoute
  '/api/health': typeof ApiHealthRoute
  '/api/vehicles': typeof ApiVehiclesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/documents/$id': typeof ApiDocumentsIdRoute
  '/api/documents/upload': typeof ApiDocumentsUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/biblioteca'
    | '/consulta'
    | '/dicas'
    | '/historico'
    | '/moderacao'
    | '/perfil'
    | '/privacidade'
    | '/termos'
    | '/veiculos'
    | '/videos'
    | '/api/health'
    | '/api/vehicles'
    | '/api/auth/$'
    | '/api/documents/$id'
    | '/api/documents/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/biblioteca'
    | '/consulta'
    | '/dicas'
    | '/historico'
    | '/moderacao'
    | '/perfil'
    | '/privacidade'
    | '/termos'
    | '/veiculos'
    | '/videos'
    | '/api/health'
    | '/api/vehicles'
    | '/api/auth/$'
    | '/api/documents/$id'
    | '/api/documents/upload'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/biblioteca'
    | '/consulta'
    | '/dicas'
    | '/historico'
    | '/moderacao'
    | '/perfil'
    | '/privacidade'
    | '/termos'
    | '/veiculos'
    | '/videos'
    | '/api/health'
    | '/api/vehicles'
    | '/api/auth/$'
    | '/api/documents/$id'
    | '/api/documents/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BibliotecaRoute: typeof BibliotecaRoute
  ConsultaRoute: typeof ConsultaRoute
  DicasRoute: typeof DicasRoute
  HistoricoRoute: typeof HistoricoRoute
  ModeracaoRoute: typeof ModeracaoRoute
  PerfilRoute: typeof PerfilRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  TermosRoute: typeof TermosRoute
  VeiculosRoute: typeof VeiculosRoute
  VideosRoute: typeof VideosRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiVehiclesRoute: typeof ApiVehiclesRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDocumentsIdRoute: typeof ApiDocumentsIdRoute
  ApiDocumentsUploadRoute: typeof ApiDocumentsUploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consulta': {
      id: '/consulta'
      path: '/consulta'
      fullPath: '/consulta'
      preLoaderRoute: typeof ConsultaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dicas': {
      id: '/dicas'
      path: '/dicas'
      fullPath: '/dicas'
      preLoaderRoute: typeof DicasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moderacao': {
      id: '/moderacao'
      path: '/moderacao'
      fullPath: '/moderacao'
      preLoaderRoute: typeof ModeracaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/veiculos': {
      id: '/veiculos'
      path: '/veiculos'
      fullPath: '/veiculos'
      preLoaderRoute: typeof VeiculosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vehicles': {
      id: '/api/vehicles'
      path: '/api/vehicles'
      fullPath: '/api/vehicles'
      preLoaderRoute: typeof ApiVehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/documents/$id': {
      id: '/api/documents/$id'
      path: '/api/documents/$id'
      fullPath: '/api/documents/$id'
      preLoaderRoute: typeof ApiDocumentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/documents/upload': {
      id: '/api/documents/upload'
      path: '/api/documents/upload'
      fullPath: '/api/documents/upload'
      preLoaderRoute: typeof ApiDocumentsUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BibliotecaRoute: BibliotecaRoute,
  ConsultaRoute: ConsultaRoute,
  DicasRoute: DicasRoute,
  HistoricoRoute: HistoricoRoute,
  ModeracaoRoute: ModeracaoRoute,
  PerfilRoute: PerfilRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  TermosRoute: TermosRoute,
  VeiculosRoute: VeiculosRoute,
  VideosRoute: VideosRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiVehiclesRoute: ApiVehiclesRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDocumentsIdRoute: ApiDocumentsIdRoute,
  ApiDocumentsUploadRoute: ApiDocumentsUploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
