const DEFAULT_EMBEDDING_MODEL='text-embedding-3-small'
export function isAIConfigured(){return Boolean(process.env.AI_BASE_URL&&process.env.AI_API_KEY)}
export function isVectorSearchConfigured(){return isAIConfigured()&&Boolean(process.env.DATABASE_URL?.match(/^postgres(ql)?:\/\//))}
const DEFAULT_CHAT_MODEL='gpt-4.1-mini'
function config(){const base=process.env.AI_BASE_URL?.replace(/\/$/,'');const key=process.env.AI_API_KEY;if(!base||!key)throw new Error('Provedor de IA não configurado. Defina AI_BASE_URL e AI_API_KEY no servidor.');return{base,key,embeddingModel:process.env.AI_EMBEDDING_MODEL||DEFAULT_EMBEDDING_MODEL,chatModel:process.env.AI_CHAT_MODEL||DEFAULT_CHAT_MODEL}}
function friendly(status:number,body:string){if(status===429)return new Error('Muitas consultas ao mesmo tempo. Tente novamente em alguns segundos.');if(status===402)return new Error('Limite financeiro do provedor de IA atingido.');if(status===403)return new Error('Acesso ao provedor de IA recusado.');return new Error(body||'Falha ao consultar a IA.')}
/** Cliente compatível com APIs no formato OpenAI. O fornecedor é escolhido apenas por variáveis de ambiente. */
export async function embedTexts(texts:string[]):Promise<number[][]>{const c=config(),out:number[][]=[];for(let i=0;i<texts.length;i+=64){const input=texts.slice(i,i+64);const r=await fetch(`${c.base}/embeddings`,{method:'POST',headers:{Authorization:`Bearer ${c.key}`,'Content-Type':'application/json'},body:JSON.stringify({model:c.embeddingModel,input})});if(!r.ok)throw friendly(r.status,(await r.text()).slice(0,300));const j=await r.json() as {data:Array<{index:number;embedding:number[]}>};out.push(...[...j.data].sort((a,b)=>a.index-b.index).map(x=>x.embedding))}return out}
export async function embedOne(text:string){const[v]=await embedTexts([text]);if(!v)throw new Error('Não foi possível interpretar a pergunta.');return v}
export async function chatComplete(system:string,user:string){const c=config();const r=await fetch(`${c.base}/chat/completions`,{method:'POST',headers:{Authorization:`Bearer ${c.key}`,'Content-Type':'application/json'},body:JSON.stringify({model:c.chatModel,messages:[{role:'system',content:system},{role:'user',content:user}]})});if(!r.ok)throw friendly(r.status,(await r.text()).slice(0,300));const j=await r.json() as {choices?:Array<{message?:{content?:string}}>};return j.choices?.[0]?.message?.content?.trim()??''}
