import { createServerFn } from '@tanstack/react-start'
import { z } from 'zod'
import { requireAuth,requireStaff } from './auth-middleware'
const askSchema=z.object({question:z.string().trim().min(5),vehicleId:z.string().uuid().nullable()})
export const askAssistant=createServerFn({method:'POST'}).middleware([requireAuth]).validator((input:unknown)=>askSchema.parse(input)).handler(async({data,context})=>{const[{answerQuestion},{checkRateLimit}]=await Promise.all([import('./rag.server'),import('./rate-limit.server')]);checkRateLimit(context.userId,'consulta',60,60_000);return answerQuestion(context.userId,data.question,data.vehicleId)})
export const processDocumentFn=createServerFn({method:'POST'}).middleware([requireAuth]).validator((input:unknown)=>z.object({documentId:z.string().uuid()}).parse(input)).handler(async({data,context})=>{const{processDocument}=await import('./rag.server');return processDocument(context.userId,data.documentId)})
export const listVehicles=createServerFn({method:'GET'}).handler(async()=>{const s=await import('./manuauto.service.server');return s.getVehicles()})
export const listMyDocuments=createServerFn({method:'GET'}).middleware([requireAuth]).handler(async({context})=>{const s=await import('./manuauto.service.server');return s.getMyDocuments(context.userId)})
export const listTips=createServerFn({method:'GET'}).middleware([requireAuth]).validator((input:unknown)=>z.object({vehicleId:z.string().uuid().nullable().optional(),includeOwn:z.boolean().optional()}).parse(input??{})).handler(async({data,context})=>{const s=await import('./manuauto.service.server');return s.getTips(context.userId,data)})
export const createTip=createServerFn({method:'POST'}).middleware([requireAuth]).validator((input:unknown)=>z.object({vehicleId:z.string().uuid().nullable(),engineCode:z.string().max(80).nullable(),topic:z.string().min(3).max(120),kind:z.enum(['recomendacao','defeito_cronico','macete','peca','alerta']),title:z.string().min(5).max(160),body:z.string().min(15).max(5000),partNumber:z.string().max(120).nullable(),sourceNote:z.string().max(1000).nullable()}).parse(input)).handler(async({data,context})=>{const[s,{checkRateLimit}]=await Promise.all([import('./manuauto.service.server'),import('./rate-limit.server')]);checkRateLimit(context.userId,'dica',20,3_600_000);return s.addTip(context.userId,data)})
export const voteTip=createServerFn({method:'POST'}).middleware([requireAuth]).validator((input:unknown)=>z.object({tipId:z.string().uuid(),worked:z.boolean()}).parse(input)).handler(async({data,context})=>{const[s,{checkRateLimit}]=await Promise.all([import('./manuauto.service.server'),import('./rate-limit.server')]);checkRateLimit(context.userId,'voto',100,60_000);return s.setTipVote(context.userId,data)})
export const listAnswerHistory=createServerFn({method:'GET'}).middleware([requireAuth]).handler(async({context})=>{const s=await import('./manuauto.service.server');return s.getAnswerHistory(context.userId)})
export const deleteAnswerHistory=createServerFn({method:'POST'}).middleware([requireAuth]).validator((input:unknown)=>z.object({id:z.string().uuid()}).parse(input)).handler(async({data,context})=>{const s=await import('./manuauto.service.server');return s.removeAnswer(context.userId,data.id)})
export const moderationQueue=createServerFn({method:'GET'}).middleware([requireStaff]).handler(async()=>{const s=await import('./manuauto.service.server');return s.getModerationQueue()})
export const moderateContent=createServerFn({method:'POST'}).middleware([requireStaff]).validator((input:unknown)=>z.object({kind:z.enum(['document','tip']),id:z.string().uuid(),status:z.enum(['approved','rejected'])}).parse(input)).handler(async({data})=>{const s=await import('./manuauto.service.server');return s.reviewContent(data)})
