import { and,desc,eq,sql } from 'drizzle-orm'
import { db } from '../db/client.server'
import { documents,tipVotes,tips,vehicles } from '../db/schema'
export async function getVehicles(){return db.select().from(vehicles).orderBy(vehicles.make,vehicles.model)}
export async function getMyDocuments(userId:string){return db.select().from(documents).where(eq(documents.ownerId,userId)).orderBy(desc(documents.createdAt))}
export async function getTips(userId:string,data:{vehicleId?:string|null;includeOwn?:boolean}){return db.select().from(tips).where(and(data.vehicleId?eq(tips.vehicleId,data.vehicleId):sql`true`,data.includeOwn?sql`(${tips.status}='approved' or ${tips.authorId}=${userId})`:eq(tips.status,'approved'))).orderBy(desc(tips.upvotes)).limit(50)}
export async function addTip(userId:string,data:any){const[row]=await db.insert(tips).values({...data,authorId:userId,status:'pending_review'}).returning();return row}
export async function setTipVote(userId:string,data:{tipId:string;worked:boolean}){await db.insert(tipVotes).values({tipId:data.tipId,userId,worked:data.worked}).onConflictDoUpdate({target:[tipVotes.tipId,tipVotes.userId],set:{worked:data.worked}});const result=await db.execute(sql`select count(*) filter(where worked)::int up,count(*) filter(where not worked)::int down from tip_votes where tip_id=${data.tipId}::uuid`);const counts=(result as any).rows?.[0]??(result as any)[0]??{up:0,down:0};await db.update(tips).set({upvotes:Number(counts.up),downvotes:Number(counts.down),updatedAt:new Date()}).where(eq(tips.id,data.tipId));return{upvotes:Number(counts.up),downvotes:Number(counts.down),worked:data.worked}}
export async function getModerationQueue(){return{documents:await db.select().from(documents).where(and(eq(documents.visibility,'public'),eq(documents.status,'pending_review'))).orderBy(documents.createdAt),tips:await db.select().from(tips).where(eq(tips.status,'pending_review')).orderBy(tips.createdAt)}}
export async function reviewContent(data:{kind:'document'|'tip';id:string;status:'approved'|'rejected'}){if(data.kind==='document')await db.update(documents).set({status:data.status,updatedAt:new Date()}).where(eq(documents.id,data.id));else await db.update(tips).set({status:data.status,updatedAt:new Date()}).where(eq(tips.id,data.id));return{ok:true}}
