import { and,desc,eq,sql } from 'drizzle-orm'
import { db } from '../db/client.server'
import { answers,docChunks,documents,tips,videos } from '../db/schema'
import { chatComplete,embedOne,embedTexts,isAIConfigured,isVectorSearchConfigured } from './ai.server'
import { extractPdfChunks } from './pdf.server'
import { storage } from './storage.server'
import { SYSTEM_PROMPT } from './system-prompt'

export async function processDocument(userId:string,documentId:string){const[doc]=await db.select().from(documents).where(and(eq(documents.id,documentId),eq(documents.ownerId,userId))).limit(1);if(!doc)throw new Error('Documento não encontrado.');try{const bytes=await storage().get(doc.storageKey);const{pageCount,chunks}=await extractPdfChunks(Uint8Array.from(bytes).buffer);if(!chunks.length)throw new Error('O PDF não possui texto pesquisável. Será necessário OCR.');const limited=chunks.slice(0,600),vectors=isVectorSearchConfigured()?await embedTexts(limited.map(x=>x.content)):[];await db.delete(docChunks).where(eq(docChunks.documentId,documentId));for(let i=0;i<limited.length;i+=100){await db.insert(docChunks).values(limited.slice(i,i+100).map((chunk,j)=>({documentId,vehicleId:doc.vehicleId,page:chunk.page,section:chunk.section,content:chunk.content,embedding:vectors[i+j]??null})))}const status=doc.visibility==='public'?'pending_review':'approved';await db.update(documents).set({status,pageCount,chunkCount:limited.length,errorMessage:null,updatedAt:new Date()}).where(eq(documents.id,documentId));return{pageCount,chunkCount:limited.length,truncated:chunks.length>limited.length,searchMode:vectors.length?'hybrid':'lexical'}}catch(cause){const message=cause instanceof Error?cause.message:'Falha ao processar o documento.';await db.update(documents).set({status:'failed',errorMessage:message,updatedAt:new Date()}).where(eq(documents.id,documentId));throw new Error(message)}}

function rowsOf(result:any):any[]{return Array.isArray(result)?result:(result?.rows??[])}
async function searchChunks(userId:string,question:string,vehicleId:string|null){const vehicleFilter=vehicleId?sql`and c.vehicle_id = ${vehicleId}::uuid`:sql``;if(isVectorSearchConfigured()){const vector=await embedOne(question);const literal=`[${vector.join(',')}]`;const result=await db.execute(sql`with lexical as (select c.id,ts_rank(to_tsvector('portuguese',c.content),websearch_to_tsquery('portuguese',${question})) rank from doc_chunks c) select c.id chunk_id,c.document_id,d.title,d.source_type,c.page,c.section,c.content,1-(c.embedding <=> ${literal}::vector) similarity,coalesce(l.rank,0) lexical,((1-(c.embedding <=> ${literal}::vector))*.75+least(coalesce(l.rank,0),1)*.25) score from doc_chunks c join documents d on d.id=c.document_id left join lexical l on l.id=c.id where c.embedding is not null ${vehicleFilter} and (d.owner_id=${userId} or (d.visibility='public' and d.status='approved')) order by score desc limit 8`);return rowsOf(result)}const result=await db.execute(sql`select c.id chunk_id,c.document_id,d.title,d.source_type,c.page,c.section,c.content,ts_rank(to_tsvector('portuguese',c.content),websearch_to_tsquery('portuguese',${question})) lexical from doc_chunks c join documents d on d.id=c.document_id where to_tsvector('portuguese',c.content) @@ websearch_to_tsquery('portuguese',${question}) ${vehicleFilter} and (d.owner_id=${userId} or (d.visibility='public' and d.status='approved')) order by lexical desc limit 8`);return rowsOf(result)}

export async function answerQuestion(userId:string,question:string,vehicleId:string|null){const rows=await searchChunks(userId,question,vehicleId);const tipRows=await db.select().from(tips).where(and(eq(tips.status,'approved'),vehicleId?eq(tips.vehicleId,vehicleId):sql`true`)).orderBy(desc(tips.upvotes)).limit(5);const community=tipRows.map((t:any)=>({id:t.id,title:t.title,body:t.body,kind:t.kind,topic:t.topic,partNumber:t.partNumber,sourceNote:t.sourceNote,engineCode:t.engineCode,upvotes:t.upvotes,downvotes:t.downvotes}));const sources=rows.map((r:any)=>({documentId:r.document_id,title:r.title,sourceType:r.source_type,page:r.page,section:r.section,excerpt:r.content.slice(0,420)}));let answer:string;if(!rows.length&&!community.length)answer='Não encontrei isso nos documentos deste veículo. Envie outro manual ou uma nota técnica para ampliar a biblioteca.';else if(isAIConfigured()){const context=rows.map((r:any,i:number)=>`[${i+1}] ${r.title}, página ${r.page??'?'}${r.section?`, seção ${r.section}`:''}\n${r.content}`).join('\n\n---\n\n'),tipContext=community.map((t:any,i:number)=>`[D${i+1}] ${t.title}\n${t.body}`).join('\n\n');answer=(await chatComplete(SYSTEM_PROMPT,`PERGUNTA:\n${question}\n\nDOCUMENTOS:\n${context||'Nenhum'}\n\nCOMUNIDADE:\n${tipContext||'Nenhuma'}`)).replace(/BUSCA_YOUTUBE:.*$/m,'').trim()}else answer=`Encontrei ${rows.length} trecho(s) relacionado(s). Sem modelo generativo configurado, confira as páginas citadas; o Manuauto não transforma automaticamente esses trechos em diagnóstico.`;const[saved]=await db.insert(answers).values({userId,vehicleId,question,answer,sources}).returning({id:answers.id});const videoRows=vehicleId?await db.select().from(videos).where(and(eq(videos.vehicleId,vehicleId),eq(videos.approved,true))).limit(6):[];return{answerId:saved?.id??null,answer,sources,tips:community,youtubeSearch:`https://www.youtube.com/results?search_query=${encodeURIComponent(question)}`,videos:videoRows.map((v:any)=>({id:v.id,title:v.title,url:v.youtubeUrl,component:v.component})),searchMode:isVectorSearchConfigured()?'hybrid':'lexical'}}
