import { GetObjectCommand,PutObjectCommand,DeleteObjectCommand,S3Client } from '@aws-sdk/client-s3'
import { mkdir,readFile,rm,writeFile } from 'node:fs/promises'
import { dirname,join,normalize } from 'node:path'
export type StoredObject={key:string;bytes:Uint8Array;contentType:string}
interface ObjectStorage{put(object:StoredObject):Promise<void>;get(key:string):Promise<Uint8Array>;delete(key:string):Promise<void>}
function safeKey(key:string){const clean=normalize(key).replace(/^(\.\.(\/|\\|$))+/,'').replace(/^[/\\]+/,'');if(clean.includes('..'))throw new Error('Chave de arquivo inválida.');return clean}
class LocalStorage implements ObjectStorage{root=process.env.LOCAL_STORAGE_DIR||'./.data/uploads';async put(o:StoredObject){const path=join(this.root,safeKey(o.key));await mkdir(dirname(path),{recursive:true});await writeFile(path,o.bytes)}async get(key:string){return new Uint8Array(await readFile(join(this.root,safeKey(key))))}async delete(key:string){await rm(join(this.root,safeKey(key)),{force:true})}}
class S3Storage implements ObjectStorage{client:S3Client;bucket:string;constructor(){this.bucket=process.env.S3_BUCKET||'';if(!this.bucket)throw new Error('S3_BUCKET não configurado.');this.client=new S3Client({region:process.env.S3_REGION||'auto',endpoint:process.env.S3_ENDPOINT,forcePathStyle:process.env.S3_FORCE_PATH_STYLE==='true',credentials:process.env.S3_ACCESS_KEY_ID?{accessKeyId:process.env.S3_ACCESS_KEY_ID,secretAccessKey:process.env.S3_SECRET_ACCESS_KEY||''}:undefined})}async put(o:StoredObject){await this.client.send(new PutObjectCommand({Bucket:this.bucket,Key:safeKey(o.key),Body:o.bytes,ContentType:o.contentType}))}async get(key:string){const r=await this.client.send(new GetObjectCommand({Bucket:this.bucket,Key:safeKey(key)}));if(!r.Body)throw new Error('Arquivo não encontrado.');return new Uint8Array(await r.Body.transformToByteArray())}async delete(key:string){await this.client.send(new DeleteObjectCommand({Bucket:this.bucket,Key:safeKey(key)}))}}
let instance:ObjectStorage|undefined
export function storage(){if(instance)return instance;const driver=process.env.STORAGE_DRIVER||'local';if(process.env.NODE_ENV==='production'&&driver==='local'&&process.env.ALLOW_LOCAL_STORAGE_PRODUCTION!=='true')throw new Error('Configure STORAGE_DRIVER=s3 ou autorize explicitamente armazenamento local persistente.');return instance=driver==='s3'?new S3Storage():new LocalStorage()}
